# azure-pipelines.yml

pool:
  vmImage: 'macOS 10.14'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '9.7.1'
  displayName: 'Install Node'

- script: npm install
  displayName: 'Install dependencies'

- script: npm run lint
  displayName: 'Run lint'

- script: npm run test
  displayName: 'Run unit tests'

- task: InstallAppleCertificate@2
  inputs:
    certSecureFile: AppleDeveloperCertificate.p12
    certPwd: $(P12password)
    keychain: 'temp'
    deleteCert: true
  displayName: Install Apple Certificate

